# https://travis-ci.org/mre/kafka-influxdb
sudo: false
os:
  - linux
  - osx
env:
  global:
    - NEWEST_PYTHON=3.4
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - pypy3
install: "pip install -r requirements.txt"
script: nosetests
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then pip install python-coveralls && coveralls; fi
