# https://travis-ci.org/mre/kafka-influxdb
sudo: false
os:
  - linux
env:
  global:
    - NEWEST_PYTHON=3.5
language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
  - "3.5-dev"
  - "nightly"
matrix:
  allow-failures:
    - python: "3.5-dev"
    - python: "nightly"
  fast_finish: true
install:
  - "pip install nose"
  - "pip install ."
script:
  - python setup.py nosetests --with-coverage
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then pip install python-coveralls coverage && coveralls; fi
