# https://travis-ci.org/mre/kafka-influxdb
sudo: false
os:
  - linux
env:
  global:
    - NEWEST_PYTHON=3.5
language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
  - "3.5-dev"
  - "nightly"
matrix:
  allow-failures:
    - python: "3.5-dev"
    - python: "nightly"
  fast_finish: true
install:
  - "pip install pytest"
  - "pip install ."
script:
  - pytest kafka_influxdb
after_success:
  # python-coveralls doesn't like coverage 4.0 (see https://github.com/z4r/python-coveralls/issues/39)
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then pip install python-coveralls coverage==3.7.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then python setup.py nosetests --with-coverage && coveralls; fi
