# https://travis-ci.org/mre/kafka-influxdb
sudo: false
os:
  - linux
env:
  global:
    - NEWEST_PYTHON=3.5
sudo: required
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "pypy-5.3.1"
  - "nightly"
matrix:
  allow-failures:
    - python: "3.5-dev"
    - python: "nightly"
  fast_finish: true
install:
  # Install librdkafka, which is needed for the high-performance confluent Kafka consumer.
  # PyPy has problems with librdkafka: "undefined symbol: PyUnicode_FromFormat". Skip for this platform.
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && sudo make install && cd ../; fi
  - "pip install ."
script:
  - python setup.py nosetests
after_success:
  # python-coveralls doesn't like coverage 4.0 (see https://github.com/z4r/python-coveralls/issues/39)
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then pip install python-coveralls coverage==3.7.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then python setup.py nosetests --with-coverage && coveralls; fi
