# https://travis-ci.org/mre/kafka-influxdb
sudo: false
os:
  - linux
  - osx
language: python
python:
  - "2.7"
  - pypy
  # Coming soon
  #- 3.3
  #- 3.4
  #- pypy3
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - pip install -r requirements.txt
script:
  - python setup.py install
  - nosetests --with-coverage
after_success:
  - coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then coveralls; fi
