---
kafka:
  host: "kafka"
  port: 9092
  group: "kafka-influxdb"
  topic: "metrics"
influxdb:
  host: "influxdb"
  port: 8086
  user: "root"
  password: "root"
  dbname: "metrics"
  use_ssl: false
  retention_policy: "default"
  time_precision: "s"
encoder: "collectd_graphite_encoder"
benchmark: false
buffer_size: 1000
statistics: true
