--- 
kafka:
  host: "10.1.3.235"
  port: 9092
  topic: "perfmonspring1"
influxdb:
  host: "springfield02.local"
  port: 8086
  user: 'root'
  password: 'root'
  dbname: 'mydb'
  version: 0.9
  retention_policy: "my_rp"
buffer_size: 1000
verbose: false
statistics: true