---
kafka:
  host: "kafka"
  port: 9092
  topic: "metrics"
  group: "kafka-influxdb"
influxdb:
  host: "influxdb"
  port: 8086
  user: "root"
  password: "root"
  dbname: "metrics"
  use_ssl: false
  verify_ssl: False
  timeout: 5
  use_udp: False
  retention_policy: "default"
  time_precision: "s"
encoder: "collectd_graphite_encoder"
benchmark: false
buffer_size: 1000
statistics: true
