---
kafka:
  host: "kafka"
  port: 9092
  topic: "metrics"
influxdb:
  host: "influxdb"
  port: 8086
  user: "root"
  password: "root"
  dbname: "metrics"
  retention_policy: "default"
# Possible encoders (see encoder directory for details)
# * collectd_graphite_encoder
encoder: "collectd_graphite_encoder"
buffer_size: 1000
verbose: false
statistics: true
