version: "2"

services:
  # Creates the following container setup:
  # collectd -> Kafka -> kafka-influxdb -> InfluxDB
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_CREATE_TOPICS: "metrics:1:1,benchmark:1:1,my_topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper"
  collectd:
    image: mre0/collectd
    volumes:
      - ./contrib/collectd/collectd.conf:/etc/collectd.conf
  influxdb:
    image: tutum/influxdb
    environment:
      PRE_CREATE_DB: "metrics"
    volumes:
      - ./contrib/influxdb/config.toml:/config/config.toml
    ports:
     - "2003"
     - "8083"
     - "8086"
  kafkainfluxdb:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # Uncomment the following three lines for interactive mode:
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/kafka-influxdb
